### ISSUE TITLE
latest changes cause problems with VTi images ii multiboot

### ISSUE THREAD

**Issue by gordon55** [oe-alliance/openmultiboot#25]
I just tested the recent updates of OpenATV (5.3 and 6.0) and OpenBH 0.6 in flash.
After updating the images in flash, i recognized that neither OpenPLI nor VTi as OMB image even show the list of installed images, only flash. And even worse, I got a crash as well, f.e.:

_Traceback (most recent call last):
  File "/usr/lib/enigma2/python/mytest.py", line 269, in create
    return screen(self, *arguments, **kwargs)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenMultiboot/OMBManagerList.py", line 170, in __init__
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenMultiboot/OMBManagerList.py", line 275, in populateImagesList
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenMultiboot/OMBManagerList.py", line 212, in isCompatible
UnboundLocalError: local variable 'running_box_type' referenced before assignment
Traceback (most recent call last):
  File "/usr/lib/enigma2/python/Components/ActionMap.py", line 46, in action
    res = self.actions[action]()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 231, in keyOk
    self.save()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 142, in save
    self.run()
  File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 146, in run
    plugin(session=self.session)
  File "/usr/lib/enigma2/python/Plugins/Extensions/OpenMultiboot/OMBManager.py", line 196, in OMBManager
  File "/usr/lib/enigma2/python/mytest.py", line 343, in open
    dlg.isTmp = True
AttributeError: 'NoneType' object has no attribute 'isTmp'
(PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x5fc3a058>>,('WizardActions', 'ok')) failed)_
 
Actually, I thought that the main purpose of OpenMultiboot is to support ALL CURRENT E2-Images, not only the OE-A versions. 

I'd really appreciate, if all images including PLI + VTI could be supported again als OMB images as it was before. I know, that not all images support OMB as flash image, but this is up to the people responsible for the image, and has from my perspective nothing to do if an image is supported as OMB installation.

I'm not a developer, don't know c(++)-code, but if I could help with testing, just let me know.
Thx in advance.

**Comment by arn354** [comment]
openmultiboot primary is for oe-alliance images - as openmultiboot uses boxbranding (see https://github.com/oe-alliance/openmultiboot/blob/master/README.md ) .
Any other image which does not support boxbranding might create pull-requests to get it working on their image as long the original functionality is not broken for oe-alliance images.

There is allready an issue about that - https://github.com/oe-alliance/openmultiboot/issues/23 - so i am closing here.
